### ISSUE TITLE
Containerbuy Spain

### ISSUE THREAD

**Issue by michaelseverin** [Robottiker/module_space#1]
http://www.contenedores-maritimos.net/?gclid=CjwKEAjwnebABRCjpvr13dHL8DsSJABB-ILJk3TJUZpp_n_iUzoguUGHt4dTGlo1u5SnKicW3AWcbBoCZhrw_wcB

http://www.containex.es/es/productos/contenedor-maritimo?gclid=CjwKEAjwnebABRCjpvr13dHL8DsSJABB-ILJCbNZoe8XKpUtXb3AYIYTimtp5BAGk_jCIb6T5cJxRxoC0Vfw_wcB

**Comment by ottiker** [comment]
This is the address to buy containers: [Star Container](http://www.starcontainer.es/en/).

**Contact:**
Ana Diaz
+34 956571059
sales@starcontainer.eu
