### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by mauricebasement** [Robottiker/module_space#2]
A decision has to be made, on how many people the to be planned sanitary module and energy module
has to support. It's crucial to the planning of the dimensions of its utilities. As Adi and Michi plan to live there, it has to support at least 2 people permanently, so I would suggest to plan for at least 5 person living there permanantly, to take peaks due to visit as well as long term guests into account. Of course: the bigger, the better, but especially with high energy demands costs increase.

**Comment by ottiker** [comment]
There are three container sizes, that are practical 2.5m (10"), 6m (20") and 9m (30"). Maybe we should think the other way around. Like, how many people can it support, if its a Xm container. Also how many people a container can support is also dependent on the tech we gonna use. But I agree 5 should be the minimum, better 10 😉.

@mauricebasement We could buy a container right now, I think, we should talk in more detail about the dimension requirements. How about today?

**Comment by michaelseverin** [comment]
I also think the electricity use of 5 People is minimum. But the System would need to be "replicable" anyway. Dimension requirements automaticly boil down to the question of what technology we will use. If we "replicate" some technology ourselves, the size of the thing is hard to guess, but i think the first step should still be, deciding on technology and Products, so we have the measurements. Yes lets talk today

**Comment by michaelseverin** [comment]
Here are some good examples from the sketchup Library.
[Solar Water purification Container Model](https://3dwarehouse.sketchup.com/model.html?id=u5c3b3b64-90f1-4ed8-ae8f-da84a05c539b)
[ISO 10" Container](https://3dwarehouse.sketchup.com/model.html?id=ued772365-5375-4d70-8215-d7456b108625)
[ISO 20" Container](https://3dwarehouse.sketchup.com/model.html?id=u5f0e751b-dce7-4f06-8398-f277adf025d5)
[ISO 45" HighCube Container](https://3dwarehouse.sketchup.com/model.html?id=u5f44701e-525d-41ae-b7c5-4a03c6cf6ff3)

 I have made a demo 30Days SketchUp account. There was recently a friend of Nina visiting (Gladys), who leared to use Sketchup and other tools when she studied architecture in the Dominican Republic. She is also avaliable to make exact plans for us if we deliver the measurements of the Interieur and the container size. Already made some quick tests with her.
like [this one](https://www.dropbox.com/s/m1ycx2rqdz3y8gw/Animation%20Test02.mp4?dl=0)

**Comment by ottiker** [comment]
@michaelseverin bought detailed CAD Models of all shipping containers. For the "energy cell" we bought a 20 feet container.
